### ISSUE TITLE
Question about the release date

### ISSUE THREAD

**Issue by seungjunlee96** [AmigoLab/SynthAnatomy#1]
Hi!

I found your work really fascinating and I wonder when the code and the full paper will be available?

Thanks,

Lee

**Comment by danieltudosiu** [comment]
Hi Lee,

Thank you for your interest and kind words.

We are ironing out some scaling issues at the moment and are looking at having a journal draft ready by the 13th of September.

Once the draft is done, we will release the codebase together with the draft on ArXiv.  Afterward, it will be fully dependent on the journal's review and editorial process.

Out of curiosity what would you aim to use the codebase for?

Best regards,

Dan

Edit 1: Typos and formatting.
Edit 2: Clarifications.

**Comment by seungjunlee96** [comment]
Thanks for your reply!

I felt the aim of your work will give really important insight to researchers - **"This AI model can help scientists understand what an image of a human brain looks like across a variety of ages, genders, and diseases"**. So I wanted to learn the details of your work and if available to try generating some samples with your model.

I hope things go well and look forward to your work!

Best,

Lee

**Comment by lukasfolle** [comment]
@danieltudosiu is the preprint available by now?

**Comment by danieltudosiu** [comment]
@lukasfolle The code will be released after the MICCAI 2022 SASHIMI workshop submission, which is this weekend 25th or 26th of June. Together with the preprint.

**Comment by danieltudosiu** [comment]
As an update, the work was accepted at MICCAI 2022 SASHIMI workshop and the codebase will be made public in time for their reproducibility award on the 28th of August. Please stay tuned. Preprint will follow shortly next week.

**Comment by danieltudosiu** [comment]
Update. The code and weights have been released.
